version: "3"
services:
  app-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=myDB
  app:
    build: .
    ports:
      - "9080:8080"
    depends_on:
      - app-db